version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - '27017:27017'
    networks:
      - local

  app:
    depends_on:
      - mongo
    container_name: devbills-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - local
    volumes:
      - ./:/home/app
      - app-node-modules:/home/app/node_modules

networks:
  local:
    name: local

volumes:
  app-node-modules: